# permissions for end users to edit appxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appx-editor-role
rules:
- apiGroups:
  - appx.naturelr.cc
  resources:
  - appxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appx.naturelr.cc
  resources:
  - appxes/status
  verbs:
  - get
