# permissions for end users to view appxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appx-viewer-role
rules:
- apiGroups:
  - appx.naturelr.cc
  resources:
  - appxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appx.naturelr.cc
  resources:
  - appxes/status
  verbs:
  - get
