
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - appx.naturelr.cc
  resources:
  - appxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appx.naturelr.cc
  resources:
  - appxes/finalizers
  verbs:
  - update
- apiGroups:
  - appx.naturelr.cc
  resources:
  - appxes/status
  verbs:
  - get
  - patch
  - update
